routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('setting', 'Backend\SettingController@index')->name('setting.index');
    Route::put('setting/update', 'Backend\SettingController@update')->name('setting.update');

    Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard'], function () {
        Route::get('', 'Backend\DashboardController@index')->name('index');
    });

    Route::group(['as' => 'menu.', 'prefix' => 'menu'], function () {
        Route::get('', 'Backend\MenuController@index')->name('index');
        Route::get('/indexnp', 'Backend\MenuController@indexnp')->name('indexnp');
        Route::post('', 'Backend\MenuController@store')->name('store');
        Route::put('', 'Backend\MenuController@update')->name('update');
        Route::get('{menu}', 'Backend\MenuController@destroy')->name('destroy');

        Route::group(['as' => 'subMenu.'], function () {
            Route::post('{menu}/subMenu', 'Backend\MenuController@storeSubMenu')->name('store');
            Route::get('{menu}/subMenu/{subMenu}', 'Backend\MenuController@destroySubMenu')->name('destroy');
            Route::get('{menu}/subMenuModal', 'Backend\MenuController@subMenuModal')->name('component.modal');

            // Route::group(['as' => 'childsubMenu.'], function () {
            //     Route::post('{subMenu}/subMenu/childsubMenu', 'Backend\MenuController@storeChildSubMenu')->name('store');
            //     Route::get('{menu}/subMenu/{subMenu}/childsubMenu/{childSubMenu}', 'Backend\MenuController@destroyChildSubMenu')->name('destroy');
            //     Route::get('{subMenu}/subMenu/childsubMenuModal', 'Backend\MenuController@childsubMenuModal')->name('component.modal');
            // });
        });
    });

    /*
        |--------------------------------------------------------------------------
        | Page CRUD Routes
        |--------------------------------------------------------------------------
        */
    Route::group(['as' => 'page.', 'prefix' => 'page'], function () {
        Route::get('', 'Backend\PageController@index')->name('index');
        Route::get('create', 'Backend\PageController@create')->name('create');
        Route::post('', 'Backend\PageController@store')->name('store');
        // Route::get('{page}', 'Backend\PageController@show')->name('show');
        Route::get('{page}/edit', 'Backend\PageController@edit')->name('edit');
        Route::put('{page}', 'Backend\PageController@update')->name('update');
        Route::get('{id}', 'Backend\PageController@destroy')->name('destroy');
    });

    Route::group(['as' => 'slider.', 'prefix' => 'slider'], function () {
        Route::get('', 'Backend\SliderController@index')->name('index');
        Route::get('create', 'Backend\SliderController@create')->name('create');
        Route::post('', 'Backend\SliderController@store')->name('store');
        Route::put('{slider}', 'Backend\SliderController@update')->name('update');
        Route::get('{slider}/edit', 'Backend\SliderController@edit')->name('edit');
        Route::get('{id}', 'Backend\SliderController@destroy')->name('destroy');

    });

    Route::group(['as' => 'category.', 'prefix' => 'category'], function () {
        Route::get('', 'Backend\CategoryController@index')->name('index');
        Route::get('create', 'Backend\CategoryController@create')->name('create');
        Route::post('', 'Backend\CategoryController@store')->name('store');
        Route::put('{category}', 'Backend\CategoryController@update')->name('update');
        Route::get('{category}/edit', 'Backend\CategoryController@edit')->name('edit');
        Route::get('{id}', 'Backend\CategoryController@destroy')->name('destroy');

    });

    Route::group(['as' => 'product.', 'prefix' => 'product'], function () {
        Route::get('', 'Backend\ProductController@index')->name('index');
        Route::get('create', 'Backend\ProductController@create')->name('create');
        Route::post('', 'Backend\ProductController@store')->name('store');
        Route::put('{product}', 'Backend\ProductController@update')->name('update');
        Route::get('{product}/edit', 'Backend\ProductController@edit')->name('edit');
        Route::get('{id}', 'Backend\ProductController@destroy')->name('destroy');

    });

    Route::group(['as' => 'event.', 'prefix' => 'event'], function () {
        Route::get('', 'Backend\EventController@index')->name('index');
        Route::get('create', 'Backend\EventController@create')->name('create');
        Route::post('', 'Backend\EventController@store')->name('store');
        Route::put('{event}', 'Backend\EventController@update')->name('update');
        Route::get('{event}/edit', 'Backend\EventController@edit')->name('edit');
        Route::get('{id}', 'Backend\EventController@destroy')->name('destroy');

    });

    Route::group(['as' => 'client.', 'prefix' => 'client'], function () {
        Route::get('', 'Backend\ClientController@index')->name('index');
        Route::get('create', 'Backend\ClientController@create')->name('create');
        Route::post('', 'Backend\ClientController@store')->name('store');
        Route::put('{client}', 'Backend\ClientController@update')->name('update');
        Route::get('{client}/edit', 'Backend\ClientController@edit')->name('edit');
        Route::get('{id}', 'Backend\ClientController@destroy')->name('destroy');

    });

    Route::group(['as' => 'gallery.', 'prefix' => 'gallery'], function () {
        Route::get('', 'Backend\GalleryController@index')->name('index');
        Route::get('create', 'Backend\GalleryController@create')->name('create');
        Route::post('', 'Backend\GalleryController@store')->name('store');
        Route::put('{gallery}', 'Backend\GalleryController@update')->name('update');
        Route::get('{id}/edit', 'Backend\GalleryController@edit')->name('edit');
        Route::get('{id}', 'Backend\GalleryController@destroy')->name('destroy');

    });

    Route::group(['as' => 'album.', 'prefix' => 'album'], function () {
        Route::get('', 'Backend\AlbumController@index')->name('index');
        Route::get('create', 'Backend\AlbumController@create')->name('create');
        Route::post('', 'Backend\AlbumController@store')->name('store');
        Route::put('{album}', 'Backend\AlbumController@update')->name('update');
        Route::get('{album}/edit', 'Backend\AlbumController@edit')->name('edit');
        Route::get('{id}', 'Backend\AlbumController@destroy')->name('destroy');

    });

    Route::group(['as' => 'team.', 'prefix' => 'team'], function () {
        Route::get('', 'Backend\TeamController@index')->name('index');
        Route::get('create', 'Backend\TeamController@create')->name('create');
        Route::post('', 'Backend\TeamController@store')->name('store');
        Route::put('{team}', 'Backend\TeamController@update')->name('update');
        Route::get('{team}/edit', 'Backend\TeamController@edit')->name('edit');
        Route::get('{id}', 'Backend\TeamController@destroy')->name('destroy');
    });

    Route::group(['as' => 'booking.', 'prefix' => 'booking'], function () {
        Route::get('', 'Backend\BookingController@index')->name('index');
        Route::get('create', 'Backend\BookingController@create')->name('create');
        Route::post('', 'Backend\BookingController@store')->name('store');
        Route::put('{booking}', 'Backend\BookingController@update')->name('update');
        Route::get('{booking}/edit', 'Backend\BookingController@edit')->name('edit');
        Route::get('{id}', 'Backend\BookingController@destroy')->name('destroy');

    });

    Route::group(['as' => 'testimonial.', 'prefix' => 'testimonial'], function () {
        Route::get('', 'Backend\TestimonialController@index')->name('index');
        Route::get('create', 'Backend\TestimonialController@create')->name('create');
        Route::post('', 'Backend\TestimonialController@store')->name('store');
        Route::put('{testimonial}', 'Backend\TestimonialController@update')->name('update');
        Route::get('{testimonial}/edit', 'Backend\TestimonialController@edit')->name('edit');
        Route::get('{id}', 'Backend\TestimonialController@destroy')->name('destroy');

    });

});

Route::get('', 'Frontend\FrontendController@homepage')->name('homepage');

Route::get('about', 'Frontend\FrontendController@about')->name('about');
Route::get('sectors', 'Frontend\FrontendController@sectorsList')->name('sectors');
Route::get('projects', 'Frontend\FrontendController@projectsList')->name('projects');
Route::get('eventdetail/{events}', 'Frontend\FrontendController@eventsDetail')->name('events.detail');
Route::get('gallery', 'Frontend\FrontendController@gallery')->name('gallery');
Route::get('sectorsdetail/{sectors}', 'Frontend\FrontendController@sectorsDetail')->name('sectors.detail');
Route::get('timelines', 'Frontend\FrontendController@timeline')->name('timeline');
Route::get('contact', 'Frontend\FrontendController@contact')->name('contact');
Route::post('contact', 'Frontend\FrontendController@sendcontact')->name('send-contact');
Route::get('faq', 'Frontend\FrontendController@faq')->name('faq');
Route::get('teams', 'Frontend\FrontendController@teams')->name('teams');
Route::get('downloads', 'Frontend\FrontendController@downloads')->name('download');
Route::get('projectsdetail/{projects}', 'Frontend\FrontendController@projectsDetail')->name('projects.detail');

app/Models/Category/Category.php
<?php

namespace App\Models\Category;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use Sluggable;

    protected $path ='uploads/category';

    public function sluggable(){
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }



    protected $fillable = [
        'slug',
        'title',
        'meta_description',
        'image',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected $appends = [
        'thumbnail_path', 'image_path'
    ];

    function getImagePathAttribute(){
        return $this->path.'/'. $this->image;
    }

    function getThumbnailPathAttribute(){
        return $this->path.'/thumb/'. $this->image;
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\CategoryRequest;
use App\Models\Category\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    function __construct(Category $category)
    {
        $this->category = $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = $this->category->orderBy('created_at', 'desc')->get();

        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backend.category.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        //
        if ($category = $this->category->create($request->data())) {
            if ($request->hasFile('image')) {
                $this->uploadFile($request, $category);
            }
        }

        return redirect()->route('category.index')->withSuccess(trans('New Category has been created'));


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //

        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        //
        if($category->update($request->data())) {
            $category->fill([
                'slug' => $request->title,
            ])->save();
            if ($request->hasFile('image')) {
                $this->uploadFile($request, $category);
            }
            return redirect()->route('category.index')->withSuccess(trans('Category has been updated'));

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category = $this->category->find($id);
        $category->delete();
        return redirect()->route('category.index')->withSuccess(trans('Category has been deleted'));
    }

    function uploadFile(Request $request, $category)
    {
        $file = $request->file('image');
        $path = 'uploads/category';
        $fileName = $this->uploadFromAjax($file, $path);
        if (!empty($category->image))
            $this->__deleteImages($category);

        $data['image'] = $fileName;
        $this->updateImage($category->id, $data);

    }

    public function __deleteImages($subCat)
    {
        try {
            if (is_file($subCat->image_path))
                unlink($subCat->image_path);

            if (is_file($subCat->thumbnail_path))
                unlink($subCat->thumbnail_path);
        } catch (\Exception $e) {

        }
    }

    public function updateImage($categoryId, array $data)
    {
        try {
            $category = $this->category->find($categoryId);
            $category = $category->update($data);
            return $category;
        } catch (Exception $e) {
            //$this->logger->error($e->getMessage());
            return false;
        }
    }
}

resources/views/backend/category/partials/form.blade.php
@csrf
<div class="row">
    <div class="col-sm-9">
        <div class="card">
            <div class="card-underline">
                <div class="card-head">
                    <header>{!! $header !!}</header>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <input type="text" name="title" class="form-control" required
                                       value="{{ old('title', isset($category->title) ? $category->title : '') }}"/>
                                <label for="title">Title</label>
                                <span id="textarea1-error" class="text-danger">{{ $errors->first('title') }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <textarea type="text" name="meta_description" class="form-control">{{old('meta_description',isset($category->meta_description)?$category->meta_description : '')}}</textarea>
                                <label for="specialization">Short Description</label>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <label class="text-default-light">Image</label>
                            @if(isset($category) && $category->image)
                                <input type="file" name="image" class="dropify"
                                    data-default-file="{{ asset($category->thumbnail_path)}}"/>
                            @else
                                <input type="file" name="image" class="dropify"/>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="" data-spy="affix" data-offset-top="50">
            <div class="panel-group" id="accordion1">
                <div class="card panel expanded">
                    <div class="card-head" data-toggle="collapse" data-parent="#accordion1" data-target="#accordion1-1">
                        <header>Publish</header>
                        <div class="tools">
                            <a class="btn btn-icon-toggle"><i class="fa fa-angle-down"></i></a>
                        </div>
                    </div>
                    <div id="accordion1-1" class="collapse in">
                        <div class="card-actionbar">
                            <div class="card-actionbar-row">
                                <a class="btn btn-default btn-ink" href="{{ route('category.index') }}">
                                    <i class="md md-arrow-back"></i>
                                    Back
                                </a>
                                <input type="submit" name="pageSubmit" class="btn btn-info ink-reaction" value="Save">
                            </div>
                        </div>
                    </div>
                </div>
                <!--end .panel --><!--end .panel --><!--end .panel --><!--end .panel -->
                {{--            </div><!--end .panel-group -->--}}
                {{--        <div class="panel-group" id="accordion1">--}}

                <!--end .panel --><!--end .panel --><!--end .panel --><!--end .panel -->
            </div><!--end .panel-group -->
        </div>
    </div>
</div>
@section('scripts')
    <script src="{{ asset('resources/js/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('resources/js/libs/jquery-validation/dist/additional-methods.min.js') }}"></script>
@endsection

resources/views/backend/category/partials/table.blade.php
<tr>
    <td>{{++$key}}</td>
    <td><img src="{{asset($category->thumbnail_path)}}" class="img-circle width-1" alt="category_image" width="50" height="50"></td>
    <td class="text-center">{{ Str::limit($category->title, 47) }}</td>
    <td>{{ Str::limit($category->meta_description, 47) }}</td>

    <td class="text-right">
        <a href="{{route('category.edit', $category->slug)}}" class="btn btn-flat btn-primary btn-xs" title="edit">
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        <a href="{{ route('category.destroy', $category->id) }}">
            <button type="button"
                class="btn btn-flat btn-danger btn-xs item-delename="delete">
                <i class="glyphicon glyphicon-trash"></i>
            </button>
    </td>
</tr>