routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');



Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('setting', 'Backend\SettingController@index')->name('setting.index');
    Route::put('setting/update', 'Backend\SettingController@update')->name('setting.update');

    Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard'], function () {
        Route::get('', 'Backend\DashboardController@index')->name('index');
    });

    Route::group(['as' => 'menu.', 'prefix' => 'menu'], function () {
        Route::get('', 'Backend\MenuController@index')->name('index');
        Route::get('/indexnp', 'Backend\MenuController@indexnp')->name('indexnp');
        Route::post('', 'Backend\MenuController@store')->name('store');
        Route::put('', 'Backend\MenuController@update')->name('update');
        Route::get('{menu}', 'Backend\MenuController@destroy')->name('destroy');

        Route::group(['as' => 'subMenu.'], function () {
            Route::post('{menu}/subMenu', 'Backend\MenuController@storeSubMenu')->name('store');
            Route::get('{menu}/subMenu/{subMenu}', 'Backend\MenuController@destroySubMenu')->name('destroy');
            Route::get('{menu}/subMenuModal', 'Backend\MenuController@subMenuModal')->name('component.modal');

            // Route::group(['as' => 'childsubMenu.'], function () {
            //     Route::post('{subMenu}/subMenu/childsubMenu', 'Backend\MenuController@storeChildSubMenu')->name('store');
            //     Route::get('{menu}/subMenu/{subMenu}/childsubMenu/{childSubMenu}', 'Backend\MenuController@destroyChildSubMenu')->name('destroy');
            //     Route::get('{subMenu}/subMenu/childsubMenuModal', 'Backend\MenuController@childsubMenuModal')->name('component.modal');
            // });
        });
    });

    /*
        |--------------------------------------------------------------------------
        | Page CRUD Routes
        |--------------------------------------------------------------------------
        */
    Route::group(['as' => 'page.', 'prefix' => 'page'], function () {
        Route::get('', 'Backend\PageController@index')->name('index');
        Route::get('create', 'Backend\PageController@create')->name('create');
        Route::post('', 'Backend\PageController@store')->name('store');
        // Route::get('{page}', 'Backend\PageController@show')->name('show');
        Route::get('{page}/edit', 'Backend\PageController@edit')->name('edit');
        Route::put('{page}', 'Backend\PageController@update')->name('update');
        Route::get('{id}', 'Backend\PageController@destroy')->name('destroy');
    });

    Route::group(['as' => 'slider.', 'prefix' => 'slider'], function () {
        Route::get('', 'Backend\SliderController@index')->name('index');
        Route::get('create', 'Backend\SliderController@create')->name('create');
        Route::post('', 'Backend\SliderController@store')->name('store');
        Route::put('{slider}', 'Backend\SliderController@update')->name('update');
        Route::get('{slider}/edit', 'Backend\SliderController@edit')->name('edit');
        Route::get('{id}', 'Backend\SliderController@destroy')->name('destroy');

    });

    Route::group(['as' => 'category.', 'prefix' => 'category'], function () {
        Route::get('', 'Backend\CategoryController@index')->name('index');
        Route::get('create', 'Backend\CategoryController@create')->name('create');
        Route::post('', 'Backend\CategoryController@store')->name('store');
        Route::put('{category}', 'Backend\CategoryController@update')->name('update');
        Route::get('{category}/edit', 'Backend\CategoryController@edit')->name('edit');
        Route::get('{id}', 'Backend\CategoryController@destroy')->name('destroy');

    });

    Route::group(['as' => 'product.', 'prefix' => 'product'], function () {
        Route::get('', 'Backend\ProductController@index')->name('index');
        Route::get('create', 'Backend\ProductController@create')->name('create');
        Route::post('', 'Backend\ProductController@store')->name('store');
        Route::put('{product}', 'Backend\ProductController@update')->name('update');
        Route::get('{product}/edit', 'Backend\ProductController@edit')->name('edit');
        Route::get('{id}', 'Backend\ProductController@destroy')->name('destroy');

    });

    Route::group(['as' => 'event.', 'prefix' => 'event'], function () {
        Route::get('', 'Backend\EventController@index')->name('index');
        Route::get('create', 'Backend\EventController@create')->name('create');
        Route::post('', 'Backend\EventController@store')->name('store');
        Route::put('{event}', 'Backend\EventController@update')->name('update');
        Route::get('{event}/edit', 'Backend\EventController@edit')->name('edit');
        Route::get('{id}', 'Backend\EventController@destroy')->name('destroy');

    });

    Route::group(['as' => 'client.', 'prefix' => 'client'], function () {
        Route::get('', 'Backend\ClientController@index')->name('index');
        Route::get('create', 'Backend\ClientController@create')->name('create');
        Route::post('', 'Backend\ClientController@store')->name('store');
        Route::put('{client}', 'Backend\ClientController@update')->name('update');
        Route::get('{client}/edit', 'Backend\ClientController@edit')->name('edit');
        Route::get('{id}', 'Backend\ClientController@destroy')->name('destroy');

    });

    Route::group(['as' => 'gallery.', 'prefix' => 'gallery'], function () {
        Route::get('', 'Backend\GalleryController@index')->name('index');
        Route::get('create', 'Backend\GalleryController@create')->name('create');
        Route::post('', 'Backend\GalleryController@store')->name('store');
        Route::put('{gallery}', 'Backend\GalleryController@update')->name('update');
        Route::get('{id}/edit', 'Backend\GalleryController@edit')->name('edit');
        Route::get('{id}', 'Backend\GalleryController@destroy')->name('destroy');

    });

    Route::group(['as' => 'album.', 'prefix' => 'album'], function () {
        Route::get('', 'Backend\AlbumController@index')->name('index');
        Route::get('create', 'Backend\AlbumController@create')->name('create');
        Route::post('', 'Backend\AlbumController@store')->name('store');
        Route::put('{album}', 'Backend\AlbumController@update')->name('update');
        Route::get('{album}/edit', 'Backend\AlbumController@edit')->name('edit');
        Route::get('{id}', 'Backend\AlbumController@destroy')->name('destroy');

    });

    Route::group(['as' => 'team.', 'prefix' => 'team'], function () {
        Route::get('', 'Backend\TeamController@index')->name('index');
        Route::get('create', 'Backend\TeamController@create')->name('create');
        Route::post('', 'Backend\TeamController@store')->name('store');
        Route::put('{team}', 'Backend\TeamController@update')->name('update');
        Route::get('{team}/edit', 'Backend\TeamController@edit')->name('edit');
        Route::get('{id}', 'Backend\TeamController@destroy')->name('destroy');
    });

    Route::group(['as' => 'booking.', 'prefix' => 'booking'], function () {
        Route::get('', 'Backend\BookingController@index')->name('index');
        Route::get('create', 'Backend\BookingController@create')->name('create');
        Route::post('', 'Backend\BookingController@store')->name('store');
        Route::put('{booking}', 'Backend\BookingController@update')->name('update');
        Route::get('{booking}/edit', 'Backend\BookingController@edit')->name('edit');
        Route::get('{id}', 'Backend\BookingController@destroy')->name('destroy');

    });

    Route::group(['as' => 'testimonial.', 'prefix' => 'testimonial'], function () {
        Route::get('', 'Backend\TestimonialController@index')->name('index');
        Route::get('create', 'Backend\TestimonialController@create')->name('create');
        Route::post('', 'Backend\TestimonialController@store')->name('store');
        Route::put('{testimonial}', 'Backend\TestimonialController@update')->name('update');
        Route::get('{testimonial}/edit', 'Backend\TestimonialController@edit')->name('edit');
        Route::get('{id}', 'Backend\TestimonialController@destroy')->name('destroy');

    });

});

Route::get('', 'Frontend\FrontendController@homepage')->name('homepage');

Route::get('about', 'Frontend\FrontendController@about')->name('about');
Route::get('sectors', 'Frontend\FrontendController@sectorsList')->name('sectors');
Route::get('projects', 'Frontend\FrontendController@projectsList')->name('projects');
Route::get('eventdetail/{events}', 'Frontend\FrontendController@eventsDetail')->name('events.detail');
Route::get('gallery', 'Frontend\FrontendController@gallery')->name('gallery');
Route::get('sectorsdetail/{sectors}', 'Frontend\FrontendController@sectorsDetail')->name('sectors.detail');
Route::get('timelines', 'Frontend\FrontendController@timeline')->name('timeline');
Route::get('contact', 'Frontend\FrontendController@contact')->name('contact');
Route::post('contact', 'Frontend\FrontendController@sendcontact')->name('send-contact');
Route::get('faq', 'Frontend\FrontendController@faq')->name('faq');

app/Http/Controllers/Backend/AlbumController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Album\StoreAlbum;
use App\Models\Album\Album;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $album;

    function __construct(Album $album)
    {
        $this->album = $album;
    }
    public function index()
    {
        $albums = $this->album->orderBy('created_at', 'desc')->get();

        return view('backend.album.index', compact('albums'));
    }

    /**
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('backend.album.create');
    }

    /**
     * @param StoreAlbum $request
     * @return mixed
     */
    public function store(StoreAlbum $request)
    {
//        DB::transaction(function () use ($request)
//        {
//            $album = News::create($request->data());
//
//            $this->uploadRequestImage($request, $album);
//        });
//    dd($request->data());
        if ($album = $this->album->create($request->data())) {
            if ($request->hasFile('image')) {
                $this->uploadFile($request, $album);
            }
        }

        return redirect()->route('album.index')->withSuccess(trans('New News has been created'));
    }

    /**
     * @param Album $page
     * @return \Illuminate\View\View
     */
    public function edit(Album $album)
    {
        return view('backend.album.edit', compact('album'));
    }

    public function update(StoreAlbum $request, Album $album)
    {
        if ($album->update($request->data())) {
            $album->fill([
                'slug' => $request->name,
            ])->save();
            return redirect()->route('album.index')->withSuccess(trans('Album has been updated'));
          
        }

    }

    public function destroy($id)
    {
//        dd($album);
        $album = $this->album->find($id);
        $album->delete();
        return redirect()->route('album.index')->withSuccess(trans('album has been deleted'));
            }


    function uploadFile(Request $request, $album)
    {
        $file = $request->file('image');
        $path = 'uploads/album';
        $fileName = $this->uploadFromAjax($file, $path);
        if (!empty($album->image))
            $this->__deleteImages($album);

        $data['cover_image'] = $fileName;
        $this->updateImage($album->id, $data);

    }

    public function __deleteImages($subCat)
    {
        try {
            if (is_file($subCat->image_path))
                unlink($subCat->image_path);

            if (is_file($subCat->thumbnail_path))
                unlink($subCat->thumbnail_path);
        } catch (\Exception $e) {

        }
    }

    public function updateImage($albumId, array $data)
    {
        try {
            $album = $this->album->find($albumId);
            $album = $album->update($data);
            return $album;
        } catch (Exception $e) {
            //$this->logger->error($e->getMessage());
            return false;
        }
    }

}

app/Http/Controllers/Backend/BookingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Booking\Booking;
use Illuminate\Http\Request;

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct(Booking $booking)
    {
        $this->booking = $booking;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $bookings = $this->booking->orderBy('created_at', 'desc')->get();

        return view('backend.booking.index', compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Booking $booking)
    {
    

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $booking = $this->booking->find($id);
        $booking->delete();
        return redirect()->route('booking.index')->withSuccess(trans('booking has been deleted'));
    }

   
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
    
        return view('backend.dashboard.index');
    }
}

resources/views/backend/testimonial/create.blade.php
@extends('backend.layouts.admin.admin')

@section('title', 'Testimonial')

@section('content')
    <section>
        <div class="section-body">

            {{ Form::open(['route' =>'testimonial.store','class'=>'form form-validate','role'=>'form', 'files'=>true, 'novalidate']) }}
            @include('backend.testimonial.partials.form', ['header' => 'Create a testimonial'])
            {{ Form::close() }}
        </div>
    </section>
@stop

@push('styles')
    <link rel="stylesheet"href="{{ asset('backend/assets/css/dropify.min.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('backend/assets/js/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('backend/assets/js/libs/jquery-validation/dist/additional-methods.min.js') }}"></script>
    <script src="{{ asset('backend/assets/js/libs/dropify/dropify.min.js') }}"></script>
@endpush

resources/views/backend/testimonial/edit.blade.php
@extends('backend.layouts.admin.admin')

@section('title', 'Testimonial')

@section('content')
    <section>
    <div class="section-body">
            <form class="form form-validate floating-label" action="{{route('testimonial.update',$testimonial->slug)}}"
                  method="POST" enctype="multipart/form-data" novalidate>
            @method('PUT')
            @include('backend.testimonial.partials.form', ['header' => 'Edit testimonial <span class="text-primary">('.($testimonial->title).')</span>'])
            </form>
        </div>
    </section>
@stop

@push('styles')
    <link href="{{ asset('backend/css/libs/dropify/dropify.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
    <script src="{{ asset('backend/js/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('backend/js/libs/jquery-validation/dist/additional-methods.min.js') }}"></script>
    <script src="{{ asset('backend/js/libs/dropify/dropify.min.js') }}"></script>
@endpush

resources/views/backend/testimonial/index.blade.php
@extends('backend.layouts.admin.admin')

@section('title', 'Testimonal')

@section('content')
    {{-- For New backend menu bar --}}

    <section>
        <div class="section-body">
            <div class="card">
                <div class="card-head">
                    <header class="text-capitalize">Testimonals</header>
                    <div class="tools">
                        <a class="btn btn-primary ink-reaction" href="{{ route(substr(Route::currentRouteName(), 0 , strpos(Route::currentRouteName(), '.')) . '.create') }}">
                            <i class="md md-add"></i>
                            Add
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table id="example" class="table table-hover display">
                        <thead>
                        <tr>
                            <th width="5%">SN</th>
                            <th width="30%">Image</th>
                            <th width="20%">Title</th>
                            <th width="20%">Content</th>
                            <th width="20%" class="text-center">Featured</th>
                            <th width="15%" class="text-right">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @each('backend.testimonial.partials.table', $testimonials, 'testimonial')
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@stop

@push('scripts')
    <script src="{{ asset('backend/js/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('backend/js/libs/jquery-validation/dist/additional-methods.min.js') }}"></script>
    <script src="{{ asset('backend/js/libs/jquery-ui/jquery-ui.min.js') }}"></script>
    <script type="text/javascript">

        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>
@endpush